version: '3.9'

services:
  pgsql:
    build: 
      context: ./infra/pgsql
      dockerfile: Dockerfile 
    container_name: pgsql
    environment:
      POSTGRES_DB: app_turnos_laravel
      POSTGRES_USER: jhossweb
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - ./infra/pgsql/init.sql:/docker-entrypoint-initdb/init.sql
    networks:
      - app-turno

  
  composer:
    image: composer:2.7
    working_dir: /var/www
    container_name: composer
    volumes:
      - ./:/var/www
    depends_on:
      - pgsql


  server:
    build: 
      context: ./infra/php
      dockerfile: Dockerfile
    container_name: server
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    networks:
      - app-turno
    depends_on:
      - pgsql
      - composer

networks:
  app-turno:
    driver: bridge

volumes:
  pgdata: